### ISSUE TITLE
C++ systems building problem

### ISSUE THREAD

**Issue by abdoufrk** [aldebjer/pysim#13]
I've tried to build the template https://github.com/aldebjer/pysim-system-template where I extracted the zip file and I typed : python setup.py build_ext in Powershell but I'm getting this error : 

C:\Python\lib\site-packages\pysim-2.2.dev0-py3.5-win32.egg\pysim\include\CppSyst
em.hpp(7): fatal error C1083: Impossible d'ouvrir le fichier includeÿ: 'Eigen/De
nse'ÿ: No such file or directory
error: Command "C:\Program Files\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /
nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Python\lib\site-packages\pysim-2.2.dev0-py3
.5-win32.egg\pysim\include -Ipysim_system_template/systems/example_cpp_systems -
IC:\Python\lib\site-packages\numpy\core\include -IC:\Python\lib\site-packages\py
sim-2.2.dev0-py3.5-win32.egg\pysim\include -IC:\Python\lib\site-packages\numpy\c
ore\include -IC:\Boost -IC:\Python\include -IC:\Python\include -I"C:\Program Fil
es\Microsoft Visual Studio 14.0\VC\INCLUDE" -I"C:\Program Files\Microsoft Visual
 Studio 14.0\VC\ATLMFC\INCLUDE" -I"C:\Program Files\Windows Kits\10\include\10.0
.10240.0\ucrt" -I"C:\Program Files\Windows Kits\NETFXSDK\4.6.1\include\um" -I"C:
\Program Files\Windows Kits\8.1\include\\shared" -I"C:\Program Files\Windows Kit
s\8.1\include\\um" -I"C:\Program Files\Windows Kits\8.1\include\\winrt" /EHsc /T
ppysim_system_template/systems/example_cpp_systems.cpp /Fobuild\temp.win32-3.5\R
elease\pysim_system_template/systems/example_cpp_systems.obj /Zm1000" failed wit
h exit status 2

**Comment by aldebjer** [comment]
That is due to a missing path to EIGEN in the template. It is fixed in commit  d289873fd195436f87bc3ec371030c32d577b9d1

If you pull the latest changes it should now work. Please let me know if it doesnt.

**Comment by abdoufrk** [comment]
It works thank you
