### ISSUE TITLE
Inheriting in python from CPP system naming issue

### ISSUE THREAD

**Issue by freol35241** [aldebjer/pysim#9]
If inheriting in python from a pysim c++ system the python class needs to have the same name as the c++ system class otherwise pysim throws an error when initializing the system.

A workaround is to manually set the class name in python:
`Class.__name__ = 'CPPsystemname'
`

or even sneakier: 
```
obj = Class()
obj.__class__.__name__ = 'CPPsystemname'
```

**Comment by aldebjer** [comment]
Lets not be sneaky :)
